---

- name: change root password
  user: name=root password={{user.password}}
- name: add user with wheel as primary group
  user: name={{user.name}} group=wheel password={{user.password}}
- name: add auth key to the user
  authorized_key: user={{user.name}} key="{{user.public_key}}"
- name: nopassword sudo for wheel group user
  template: src=wheel.j2 dest=/etc/sudoers.d/wheel owner=root group=root mode=0440
- name: add SSH_AUTH_SOCK to env_keep
  template: src=ssh_auth_sock.j2 dest=/etc/sudoers.d/ssh_auth_sock owner=root group=root mode=0440
