---
- name: install awscli
  shell: bash -lc "pip install awscli"

- name: mkdir ~/.aws
  file: path=/root/.aws state=directory

- name: awscli config
  template: src=config.j2 dest=/root/.aws/config owner=root group=root mode=0600

- name: awscli credentials
  template: src=credentials.j2 dest=/root/.aws/credentials owner=root group=root mode=0600
