---

- name: install aws-cli on CentOS
  when: >
    ansible_distribution == "CentOS"
  pip: name="awscli" state="latest"

- name: mkdir ~/.aws
  file: path=/root/.aws state=directory
- name: awscli config
  template: src=config.j2 dest=/root/.aws/config owner=root group=root mode=0600
- name: awscli credentials
  template: src=credentials.j2 dest=/root/.aws/credentials owner=root group=root mode=0600
