---
- name: install supervisor
  shell: bash -lc "pip install supervisor"
- name: copy config
  template: src=supervisord.conf.j2 dest={{conf_location}} owner=root group=root mode=0664
- name: create conf dir
  file: path=/etc/supervisord.d state=directory
- name: make log directory
  file: path=/var/log/supervisor state=directory
- include: centos7.yml
  when: >
    ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
- name: enable supervisord
  service: name=supervisord state=started enabled=yes
