---
- name: symlink localtime file
  file: src=/usr/share/zoneinfo/Japan dest=/etc/localtime state=link force=yes
- name: update sysconfig
  replace: backup=yes dest=/etc/sysconfig/clock regexp='ZONE="UTC"' replace='ZONE="Asia/Tokyo"'
  register: result
- debug: msg="Please reboot to reflect this chenge"
  when: result.changed
