---

- name: remove vim
  yum: name=vim state=absent
  yum: name=vim-common state=absent
  yum: name=vim-enhanced state=absent
- name: install gcc
  yum: name=gcc state=latest
- name: install ncurses
  yum: name=ncurses state=latest
  yum: name=ncurses-devel state=latest
- name: install lua
  yum: name=lua state=latest
  yum: name=lua-devel state=latest
- name: clone vim source
  git: repo="https://github.com/vim/vim.git" dest={{ compiledir }}
- name: vim configure
  # to make pyenv enabled, need to compile through bash -lc
  shell: chdir={{ compiledir }} bash -lc "./configure {{ configureopts }}"
- name: vim make
  shell: chdir={{ compiledir }} make
- name: vim make install
  shell: chdir={{ compiledir }} make install
- name: make symlink
  file: src=/usr/local/vim/bin/vim dest=/usr/local/bin/vim state=link
