---

- name: remove vim
  yum: name=vim state=absent
  yum: name=vim-common state=absent
  yum: name=vim-enhanced state=absent
- name: install gcc
  yum: name=gcc state=latest
- name: install ncurses
  yum: name=ncurses state=latest
  yum: name=ncurses-devel state=latest
- name: install lua
  yum: name=lua state=latest
  yum: name=lua-devel state=latest
- name: clone vim source
  git: repo="https://github.com/vim/vim.git" dest={{ compiledir }}
- name: make source with lua enabled
  shell: >-
    bash -lc "./configure {{ configureopts }} && make && make install"
    chdir={{ compiledir }}
    creates={{ compiledir }}/src/vim
- name: make symlink
  file: src=/usr/local/vim/bin/vim dest=/usr/local/bin/vim state=link
