---

- name: install epel
  yum: name=epel-release state=latest
- name: install dev tools
  yum: name={{ item }} state=latest
  with_items: "{{ libs }}"
# - name: yum update
#   yum: name=* state=latest
  register: result
- debug: msg="Please reboot to reflect this chenge"
  when: result.changed
