---

- name: install munin
  yum: name={{item}} state=latest
  with_items:
    - munin
    - munin-node
    - munin-common

- name: enable munin-node
  service: name=munin-node state=started enabled=yes
