---

- name: configure sshd_config
  lineinfile: dest=/etc/ssh/sshd_config regexp="{{ item.regexp }}" line="{{ item.line }}" backup="{{ item.backup }}"
  with_items: "{{lines}}"
- name: restart sshd
  service: name=sshd state=restarted
